# prox_instal_nano_neovim.yml
- hosts: proxnodes
  become: true
  tasks:

  - name: update repository cache and upgrade
    apt:
      update_cache: true
      name:
      - nano
      - neovim
      status: latest
